<?php

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker\Factory::create();
        $data = [
            [
                'title_en' => 'ML Fundamental',
                'slug_en' => str_slug('ML Fundamental'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'ML Fundamental',
                'slug_vi' => str_slug('ML Fundamental'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'ML in Computer Vision',
                'slug_en' => str_slug('ML in Computer Vision'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'ML in Computer Vision',
                'slug_vi' => str_slug('ML in Computer Vision'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'ML in NLP',
                'slug_en' => str_slug('ML in NLP'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'ML in NLP',
                'slug_vi' => str_slug('ML in NLP'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'ML in Cyber Security',
                'slug_en' => str_slug('ML in Cyber Security'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'ML in Cyber Security',
                'slug_vi' => str_slug('ML in Cyber Security'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

            // product
            [
                'title_en' => 'ML in the Cloud',
                'slug_en' => str_slug('ML in the Cloud'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'ML in the Cloud',
                'slug_vi' => str_slug('ML in the Cloud'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'AI in Smart Agriculture (upcoming)',
                'slug_en' => str_slug('AI in Smart Agriculture (upcoming)'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'AI in Smart Agriculture (upcoming)',
                'slug_vi' => str_slug('AI in Smart Agriculture (upcoming)'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'AI in Smart City (upcoming)',
                'slug_en' => str_slug('AI in Smart City (upcoming)'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'AI in Smart City (upcoming)',
                'slug_vi' => str_slug('AI in Smart City (upcoming)'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'Student & PhD. candidates',
                'slug_en' => str_slug('Student & PhD. candidates'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'Student & PhD. candidates',
                'slug_vi' => str_slug('Student & PhD. candidates'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'AI in Marketing',
                'slug_en' => str_slug('AI in Marketing'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'AI in Marketing',
                'slug_vi' => str_slug('AI in Marketing'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'BigData ecosystem & architecture',
                'slug_en' => str_slug('BigData ecosystem & architecture'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'BigData ecosystem & architecture',
                'slug_vi' => str_slug('BigData ecosystem & architecture'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'Data governance in the enterprise',
                'slug_en' => str_slug('Data governance in the enterprise'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'Data governance in the enterprise',
                'slug_vi' => str_slug('Data governance in the enterprise'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'AI for Business leaders',
                'slug_en' => str_slug('AI for Business leaders'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'AI for Business leaders',
                'slug_vi' => str_slug('AI for Business leaders'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title_en' => 'Data governance in the enterprise',
                'slug_en' => str_slug('Data governance in the enterprise'),
                'description_en' => $faker->realText(200, 2),
                'title_vi' => 'Data governance in the enterprise',
                'slug_vi' => str_slug('Data governance in the enterprise'),
                'description_vi' => $faker->realText(200, 2),
                'detail_vi' => $faker->realText(500, 2),
                'detail_en' => $faker->realText(500, 2),
                'point_review_manual' => 3.5,
                'total_review_manual' => 20,
                'is_review_manual' => true,
                'point_review_avg' => 3.5,
                'total_review' => 20,
                'viewed' => 30,
                'has_vi' => true,
                'has_en' => true,
                'instructor_id' => 1,
                'image_url' => $faker->imageUrl(370, 220),
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ];

        Course::insert($data);
    }
}
